split

diff --git a/.github/workflows/build-v8-windows.yml b/.github/workflows/build-v8-windows.yml
--- a/.github/workflows/build-v8-windows.yml
+++ b/.github/workflows/build-v8-windows.yml
@@ -28,7 +28,7 @@ on:
         required: true
 
 jobs:
-  x64:
+  x64-debug:
     runs-on: windows-latest
     steps:
     - name: Checkout This Repo
@@ -59,6 +59,58 @@ jobs:
         gn gen out/x64.debug --args='v8_target_cpu=\"x64\" target_cpu=\"x64\" is_debug=true symbol_level=2 is_clang=true is_component_build=false v8_static_library=true clang_use_chrome_plugins=false v8_enable_pointer_compression=true use_custom_libcxx=false v8_enable_partition_alloc=false v8_monolithic=true v8_use_external_startup_data=false icu_use_data_file=false v8_enable_sandbox=false v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true v8_enable_temporal_support=false'
         ninja -C out/x64.debug v8_monolith v8_hello_world
 
+    - name: Test Product
+      shell: pwsh
+      run: |
+        $ErrorActionPreference = "Stop"
+        $output = .\v8\v8\out\x64.debug\v8_hello_world.exe
+        if($output -like "Hello, World!*"){
+          Write-Output "Debug test passed."
+        }
+        else{
+          Write-Error "Test failure: output is $output"
+          exit 1
+        }
+
+    - name: Compress Product
+      shell: pwsh
+      run: |
+        echo ${{inputs.version}} >> VERSION.txt
+        echo ${{inputs.commit}} >> VERSION.txt
+        mkdir temp\include
+        cp -r .\v8\v8\include\* .\temp\include
+        7z a v8_windows_x64_debug.7z .\v8\v8\out\x64.debug\obj\v8_monolith.lib .\temp\include VERSION.txt
+
+    - name: Upload Archive
+      uses: actions/upload-artifact@v4
+      with:
+        name: v8_windows_x64_debug
+        path: |
+          *.7z
+        retention-days: 7
+
+  x64-release:
+    runs-on: windows-latest
+    steps:
+    - name: Checkout This Repo
+      uses: actions/checkout@v6.0.2
+      with:
+        clean: true
+        fetch-depth: 1
+
+    - name: Prepare
+      uses: ./.github/actions/prepare
+      with:
+        googlesource_gitcookies: ${{secrets.googlesource_gitcookies}}
+
+    - name: Fetch V8
+      uses: ./.github/actions/fetch-v8
+      with:
+        commit: ${{inputs.commit}}
+
+    - name: Apply Patches
+      uses: ./.github/actions/windows-patches
+
     - name: Build Windows x64 Release
       shell: pwsh
       run: |
@@ -72,20 +124,12 @@ jobs:
       shell: pwsh
       run: |
         $ErrorActionPreference = "Stop"
-        $output1 = .\v8\v8\out\x64.debug\v8_hello_world.exe
-        if($output1 -like "Hello, World!*"){
-          Write-Output "Debug test passed."
-        }
-        else{
-          Write-Error "Test failure: output is $output1"
-          exit 1
-        }
-        $output2 = .\v8\v8\out\x64.release\v8_hello_world.exe
-        if($output2 -like "Hello, World!*"){
+        $output = .\v8\v8\out\x64.release\v8_hello_world.exe
+        if($output -like "Hello, World!*"){
           Write-Output "Release test passed."
         }
         else{
-          Write-Error "Test failure: output is $output2"
+          Write-Error "Test failure: output is $output"
           exit 1
         }
 
@@ -96,18 +140,17 @@ jobs:
         echo ${{inputs.commit}} >> VERSION.txt
         mkdir temp\include
         cp -r .\v8\v8\include\* .\temp\include
-        7z a v8_windows_x64_debug.7z .\v8\v8\out\x64.debug\obj\v8_monolith.lib .\temp\include VERSION.txt
         7z a v8_windows_x64_release.7z .\v8\v8\out\x64.release\obj\v8_monolith.lib .\temp\include VERSION.txt
 
     - name: Upload Archive
       uses: actions/upload-artifact@v4
       with:
-        name: v8_windows_x64
+        name: v8_windows_x64_release
         path: |
           *.7z
         retention-days: 7
 
-  arm64:
+  arm64-debug:
     runs-on: windows-latest
     steps:
     - name: Checkout This Repo
@@ -144,6 +187,51 @@ jobs:
         gn gen out/arm64.debug --args='v8_target_cpu=\"arm64\" target_cpu=\"arm64\" is_debug=true symbol_level=2 is_clang=true is_component_build=false v8_static_library=true clang_use_chrome_plugins=false v8_enable_pointer_compression=true use_custom_libcxx=false v8_enable_partition_alloc=false v8_monolithic=true v8_use_external_startup_data=false icu_use_data_file=false v8_enable_sandbox=false v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true v8_enable_temporal_support=false'
         ninja -C out/arm64.debug v8_monolith
 
+    - name: Compress Product
+      shell: pwsh
+      run: |
+        echo ${{inputs.version}} >> VERSION.txt
+        echo ${{inputs.commit}} >> VERSION.txt
+        mkdir temp\include
+        cp -r .\v8\v8\include\* .\temp\include
+        7z a v8_windows_arm64_debug.7z .\v8\v8\out\arm64.debug\obj\v8_monolith.lib .\temp\include VERSION.txt
+
+    - name: Upload Archive
+      uses: actions/upload-artifact@v4
+      with:
+        name: v8_windows_arm64_debug
+        path: |
+          *.7z
+        retention-days: 7
+
+  arm64-release:
+    runs-on: windows-latest
+    steps:
+    - name: Checkout This Repo
+      uses: actions/checkout@v6.0.2
+      with:
+        clean: true
+        fetch-depth: 1
+
+    - name: Prepare
+      uses: ./.github/actions/prepare
+      with:
+        googlesource_gitcookies: ${{secrets.googlesource_gitcookies}}
+
+    - name: Fetch V8
+      uses: ./.github/actions/fetch-v8
+      with:
+        commit: ${{inputs.commit}}
+
+    - name: Apply Patches
+      uses: ./.github/actions/windows-patches
+
+    - name: Install ARM64 Debugger Tools
+      uses: ChristopheLav/windows-sdk-install@v1
+      with:
+        version-sdk: 26100
+        features: "OptionId.WindowsDesktopDebuggers"
+
     - name: Build Windows arm64 Release
       shell: pwsh
       run: |
@@ -160,13 +248,12 @@ jobs:
         echo ${{inputs.commit}} >> VERSION.txt
         mkdir temp\include
         cp -r .\v8\v8\include\* .\temp\include
-        7z a v8_windows_arm64_debug.7z .\v8\v8\out\arm64.debug\obj\v8_monolith.lib .\temp\include VERSION.txt
         7z a v8_windows_arm64_release.7z .\v8\v8\out\arm64.release\obj\v8_monolith.lib .\temp\include VERSION.txt
 
     - name: Upload Archive
       uses: actions/upload-artifact@v4
       with:
-        name: v8_windows_arm64
+        name: v8_windows_arm64_release
         path: |
           *.7z
         retention-days: 7
